import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

test('AI 托管在开启面板选择运行配置，并把选择快照写入会话', () => {
  const sharedAgent = readFileSync('apps/web/src/stores/sharedAgent.ts', 'utf8');
  const workspace = readFileSync('apps/web/src/stores/codexWorkspace.ts', 'utf8');
  const conversation = readFileSync('apps/web/src/components/ButlerConversation.tsx', 'utf8');
  const panel = readFileSync('apps/web/src/components/AgentPanel.tsx', 'utf8');
  const settings = readFileSync('apps/web/src/components/AiSettings.tsx', 'utf8');

  assert.match(sharedAgent, /const workspace = useCodexWorkspace\.getState\(\)/);
  assert.match(sharedAgent, /runtimeModel: options\.runtimeModel/);
  assert.match(sharedAgent, /runtimeEffort: options\.runtimeEffort/);
  assert.match(sharedAgent, /runtimePermissionPreset: options\.runtimePermissionPreset/);
  assert.match(sharedAgent, /permissionPreset: session\?\.runtimePermissionPreset \?\? workspace\.permissionPreset/);
  assert.match(panel, /aria-label="AI 托管模型"/);
  assert.match(panel, /aria-label="AI 托管推理强度"/);
  assert.match(panel, /aria-label="AI 托管权限"/);
  assert.match(panel, /runtimeModel: hostingModel/);
  assert.match(panel, /runtimeEffort: hostingEffort/);
  assert.match(panel, /runtimePermissionPreset: hostingPermissionPreset/);
  assert.match(panel, /aria-label="DSH AI 托管模型"/);
  assert.match(panel, /aria-label="DSH AI 托管推理强度"/);
  assert.match(panel, /aria-label="DSH AI 托管 Agent"/);
  assert.match(panel, /aria-label="DSH AI 托管权限"/);
  assert.match(panel, /dshModelSelection: dshModelOverride/);
  assert.match(panel, /dshAgentPreset: dshAgentOverride/);
  assert.match(panel, /dshPermissionPreset: dshPermissionOverride/);
  assert.match(sharedAgent, /dshModelSelection: options\.dshModelSelection/);
  assert.match(sharedAgent, /dshAgentPreset: options\.dshAgentPreset/);
  assert.match(sharedAgent, /dshPermissionPreset: options\.dshPermissionPreset/);
  assert.match(sharedAgent, /prepareSharedDshStartConfiguration/);
  assert.match(sharedAgent, /createSession\(dshStartOptions\)/);
  assert.doesNotMatch(workspace, /hostingModel/);
  assert.doesNotMatch(workspace, /hostingEffort/);
  assert.doesNotMatch(workspace, /setHostingModel/);
  assert.doesNotMatch(workspace, /setHostingEffort/);
  assert.doesNotMatch(conversation, /aria-label="AI 托管设置"/);
  assert.doesNotMatch(conversation, /ariaLabel="AI 托管模型"/);
  assert.doesNotMatch(conversation, /ariaLabel="AI 托管推理强度"/);
  assert.doesNotMatch(sharedAgent, /agentHostingSettings|getAgentHostingCodexSettings/);
  assert.doesNotMatch(settings, /AI 托管 Codex 模型|AI 托管 Codex 推理强度|AI 托管 Codex 权限/);
});

test('聊天托管面板展示独立托管配置，并提供管家统一管理入口', () => {
  const panel = readFileSync('apps/web/src/components/AgentPanel.tsx', 'utf8');

  assert.match(panel, /AI 托管配置/);
  assert.match(panel, /selectedModel/);
  assert.match(panel, /selectedEffort/);
  assert.match(panel, /permissionPreset/);
  assert.match(panel, /runtimeModel/);
  assert.match(panel, /runtimeEffort/);
  assert.match(panel, /runtimePermissionPreset/);
  assert.match(panel, /开启配置/);
  assert.match(panel, /在 AI 管家中查看/);
  assert.match(panel, /openButlerConversation/);
  assert.match(panel, /workspaceRoot/);
  assert.match(panel, /availableProjects/);
  assert.match(panel, /useAgentEnvironments/);
  assert.match(panel, /environmentIsBusy/);
  assert.match(panel, /aria-label="AI 托管项目"/);
  assert.match(panel, /roomHostingWorkspaceRoot/);
  assert.match(panel, /setRoomHostingWorkspace/);
  assert.match(panel, /沿用 DSH 默认/);
  assert.match(panel, /显式模型选择同步为后续会话的默认模型/);
  assert.doesNotMatch(panel, /defaultWorkspaceRoot|butlerWorkspaceRoot|isSystemCodexWorkspace/);
  assert.doesNotMatch(panel, /临时工作区（系统默认）/);
  assert.doesNotMatch(panel, /临时选择 AI 托管项目|其他目录/);
  const chat = readFileSync('apps/web/src/components/ChatArea.tsx', 'utf8');
  assert.match(chat, /aria-label="配置 AI 托管"/);
  assert.match(chat, /title="选择项目或打开托管设置"/);
  assert.match(chat, />\s*AI 托管\s*</);
  assert.match(chat, /aria-label="打开 AI 托管控制面"/);
  assert.match(chat, /setPanel\(\{ kind: 'agent', tmid: agentSessionKey \}\)/);
  assert.match(chat, /id="room-butler-launcher"/);
  assert.match(chat, /aria-label=\{butlerPanelOpen \? '收起房间 AI' : '打开房间 AI'\}/);
  assert.match(chat, /onClick=\{\(\) => togglePanel\(\{ kind: 'butler' \}\)\}/);
  assert.match(chat, /setRoomHostingWorkspace\(activeRid, path\.path\);[\s\S]*setPanel\(\{ kind: 'agent', tmid: agentSessionKey \}\);/);
  assert.match(chat, /在 AI 管家中管理项目/);
  assert.match(chat, /openButlerConversation/);
  assert.match(chat, /setRoomHostingWorkspace\(activeRid, path\.path\)/);
  assert.doesNotMatch(chat, /butlerWorkspaceRoot|isSystemCodexWorkspace/);
});

test('开启托管会立即显示进度，并反馈跨设备前置检查失败', () => {
  const panel = readFileSync('apps/web/src/components/AgentPanel.tsx', 'utf8');

  assert.match(panel, /const startBlockReason/);
  assert.match(panel, /当前未启用 AI，请在设置中选择 Codex 或 DSH 并重启应用/);
  assert.match(panel, /这台设备尚未添加托管项目/);
  assert.match(panel, /尚未读取到可用 Codex 模型/);
  assert.match(panel, /DSH 启动配置尚未就绪/);
  assert.match(panel, /open\(\{ directory: true, multiple: false, title: '选择 AI 托管项目' \}\)/);
  assert.match(panel, /ensureEnvironment\(\{ path \}\)/);
  assert.match(panel, /environmentIsBusy\(environment\.id, environmentState\.bindings\)/);
  assert.match(panel, /updateEnvironment\(environment\.id, \{ enabled: true \}\)/);
  assert.match(panel, /if \(!selectedProject\) \{\s*void addHostingProject\(\)/);
  assert.match(panel, /添加托管项目/);
  assert.match(panel, /setStartingTmid\(tmid\)/);
  assert.match(panel, /setStartFailure/);
  assert.match(panel, /正在开启…/);
  assert.match(panel, /role="alert"/);
  assert.match(panel, /role="status"/);
  assert.match(panel, /\.catch\(\(startError\) => \{[\s\S]*toast\.error\(startError, '开启 AI 托管失败'\);[\s\S]*\}\)/);
  assert.doesNotMatch(panel, /\.catch\(\(\) => undefined\)/);
});
