import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

test('手动编辑器支持主从页面嵌入、结构化计划和原生文件同步', () => {
  const editor = readFileSync('apps/web/src/components/ButlerRoutineCreateDialog.tsx', 'utf8');

  assert.doesNotMatch(editor, /import Dialog from/);
  assert.match(editor, /role=\{embedded \? 'region' : 'dialog'\}/);
  assert.match(editor, /aria-modal=\{embedded \? undefined : true\}/);
  assert.match(editor, /butler-routine-editor-slot/);
  assert.match(editor, /butler-routine-editor\$\{embedded \? ' is-embedded'/);
  assert.match(editor, /新建已安排任务/);
  assert.match(editor, /const hasCronWorkspace = taskWorkspace === '~' \|\| !!taskWorkspace \|\| !!workspaceRoot;/);
  assert.match(editor, /<option value="daily">每天<\/option>/);
  assert.match(editor, /<option value="weekdays">工作日<\/option>/);
  assert.match(editor, /<option value="weekly">每周<\/option>/);
  assert.match(editor, /<option value="interval">按分钟间隔<\/option>/);
  assert.match(editor, /<option value="custom">自定义计划<\/option>/);
  assert.match(editor, /<option value="">当前工作区<\/option>/);
  assert.match(editor, /<option value="~">临时会话（系统管理）<\/option>/);
  assert.match(editor, /管家会话（系统管理）/);
  assert.match(editor, /<span>计划类型<\/span>/);
  assert.match(editor, /<span>分钟<\/span>/);
  assert.match(editor, /<legend>星期<\/legend>/);
  assert.match(editor, /<span>月日<\/span>/);
  assert.match(editor, /<span>月份<\/span>/);
  assert.match(editor, /<span>时间<\/span>/);
  assert.match(editor, /临时会话适合一次性任务，管家会话保留长期上下文；托管项目需先在 AI 管家左侧添加/);
  assert.match(editor, /await syncNative\(id, routine\)/);
  assert.match(editor, /await syncNative\(id, null\)/);
  assert.match(editor, /保存为 Codex 原生 automation\.toml/);
  assert.doesNotMatch(editor, /执行 Skill/);
  assert.doesNotMatch(editor, /自定义 RRULE/);
  assert.doesNotMatch(editor, /<span>RRULE<\/span>/);
});

test('已安排工作面使用 Codex 式主从结构，定义与多次运行分开展示', () => {
  const page = readFileSync('apps/web/src/pages/ButlerPage.tsx', 'utf8');
  const routines = readFileSync('apps/web/src/components/ButlerRoutines.tsx', 'utf8');

  assert.match(page, /activeView === 'routines' \? \(/);
  assert.match(routines, /<section aria-label="已安排" className=\{`butler-scheduled-workbench/);
  assert.match(routines, /<h1 className="sr-only">已安排的任务<\/h1>/);
  assert.match(routines, /className="butler-scheduled-master"/);
  assert.match(routines, /className="butler-scheduled-detail-pane"/);
  assert.match(routines, /aria-label="使用 Codex 创建已安排任务"/);
  assert.match(routines, /aria-label="选择创建方式"/);
  assert.match(routines, /使用 Codex 创建/);
  assert.match(routines, /手动设置/);
  assert.match(routines, /await startThread\('创建已安排任务'\)/);
  assert.match(routines, /await send\(CODEX_CREATE_PROMPT\)/);
  assert.match(routines, /setButlerView\('conversation'\)/);
  assert.match(routines, /aria-label="搜索已安排任务"/);
  assert.match(routines, /aria-label="已安排任务状态"/);
  assert.match(routines, /aria-label=\{`打开\$\{routine\.name\}详情`\}/);
  assert.match(routines, /aria-label=\{`立即运行\$\{selected\.name\}`\}/);
  assert.match(routines, /运行历史记录/);
  assert.match(routines, /selected\.runs\.filter\(\(run\) => !run\.archived\)\.map/);
  assert.match(routines, /<ButlerRoutineCreateDialog key=\{draft\?\.templateId \?\? 'manual'\} draft=\{draft\} embedded/);
  assert.match(routines, /<ButlerRoutineCreateDialog key=\{selected\.id\} routine=\{selected\} embedded/);
  assert.match(routines, /hydrateNative/);
  assert.match(routines, /syncNative/);
  assert.match(routines, /deleteNative/);
  assert.match(routines, /Codex 原生 automation\.toml/);
  assert.match(routines, /BUTLER_ABILITY_TEMPLATES/);
  assert.match(routines, /<h2>建议<\/h2>/);
  assert.doesNotMatch(routines, /butler-scheduled-result/);
  assert.doesNotMatch(routines, /role="article"/);
  assert.doesNotMatch(routines, /openCodexSurface\('scheduled'\)/);
});
